### ISSUE TITLE
Feature Request: Add "Report Generated: $DATE" text within the Spreadsheet and PDF

### ISSUE THREAD

**Issue by tonyyo11** [liquidz00/Patcher#7]
In the PDF, underneath the custom title it shows "MONTH YEAR". This should show the date that the report had been generated (MONTH DATE YEAR) for instances where the report is being generated more frequently than on a monthly basis.
![Screenshot 2024-04-03 at 11 23 57 AM](https://github.com/liquidz00/Patcher/assets/41205894/e2186d26-7a20-4e87-b0ac-27ea5b015a23)

Likewise within the excel spreadsheet - but also not as vital as with the PDF version.

**Comment by liquidz00** [comment]
Love this idea and definitely will be implementing it ASAP. An additional option can be passed as a flag to include the day as well as the month and year in the PDF. 

Admittedly, I'm not as proficient with the pandas library as I probably should be. I'll try to figure out a way to get it added to the excel spreadsheet as well. Design-wise, were you thinking of having the spreadsheet have similar title and date formatting as the PDF?
